config/routes.rb
StartupsAnonymous::Application.routes.draw do

  

  ActiveAdmin.routes(self)

  match '/login',  to: 'sessions#new'
  match '/logout',  to: 'sessions#destroy'

  # resources :users, only: :show
  resource :user, only: [:new, :show, :edit, :create, :update]
  get "/users/:id", to: "users#show", as: :profile

  resource :sessions

  resources :timeslots
  resource :schedule, :controller => :schedule
  resources :password_resets


  match '/listeners', to: 'pages#listeners'
  match '/about', to: 'pages#about'
  match '/resources', to: 'pages#resources'
  root to: 'pages#home'
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :name, :password, :password_confirmation, :anonymous, :role, :skype
  has_secure_password
  validates :email, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
  validates_presence_of :password, on: :create
  validates_uniqueness_of :email
  validates_presence_of :schedule

  before_create { generate_token(:auth_token)}
  after_create :default_role

  has_one :schedule
  has_many :timeslots, through: :schedule

  before_validation :build_my_schedule, :on => :create

  ROLES = %w[entrepreneur listener admin]


  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def is?(role)
    ROLES.include?(role.to_s)
  end

  def anonymous_check
    if self.anonymous? 
      "Anonymous"
    else
      self.email 
    end
  end

  #run rake task to create passwords and auth tokens for existing users
  #find path to reset passwords for existing users
  #index auth token
  
  private

  def build_my_schedule
    build_schedule
  end

  def default_role
    self.role = "entrepreneur"
    self.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authentication_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      sign_in @user
      UserMailer.confirm(@user).deliver
      redirect_to timeslots_path, notice: 'Please check your email'
    else
      redirect_to root_path, error: 'Sorry, we were unable to sign you up. Please do try again!'
    end
  end

  def show 
    @user = params[:id] ? User.find_by_id(params[:id]) : current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to user_path, notice: "Yay! Profile updated"
    else
      flash[:error] = "There was a problem updating your profile"
    render 'edit'
    end
  end

end

app/views/users/_new.html.erb
<section class='new-user'>

<%= form_for(@user, url: user_path, html: {class: 'custom', id: 'contact'}) do |f| %>
  <div class="row">
    <% if @user.errors.any? %>
      <div class="error">
        <h2>Invalid entry!</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="small-12 columns">
      <%= f.text_field :email, placeholder: 'email address', class: 'user-input' %>
    </div>
    <div class="small-12 columns">
      <div class="field">
        <%= f.password_field :password, placeholder: 'password', class: 'user-input' %>
      </div>
    </div>
    <div class="small-12 columns text-left">
      <%= f.check_box :anonymous %>
      <small>Please make me anonymous</small>
    </div>
    <div class="small-12 columns text-center">
      <%= f.submit 'Sign up', class: 'cta-button' %>
    </div>
  </div>
<% end %>

</section>

app/views/users/_skype.html.haml
= form_for user, url: user_path, html: {class: 'custom'} do |f|
  %h2 Skype
  %h4.subheader Please enter your skype username
  %div.datetime
    = f.text_field :skype
  = f.submit :submit, class: 'button prefix', id: 'skype'

app/views/users/edit.html.haml
.row
  .large-6.columns
    %h2 Edit your profile
    = form_for @user, url: user_path, html: {class: 'custom user-editing'} do |f|
      = f.label :email
      = f.text_field :email
      = f.label :anonymous?
      = f.check_box :anonymous
      = f.label :skype_username
      = f.text_field :skype
      = f.submit :submit, class: 'button prefix'
    %p= link_to "Please click here if you need to reset your password", new_password_reset_path

app/views/users/show.html.haml
.row 
  .large-6.columns
    %h1
      = link_to_if can?(:update, @user), @user.anonymous_check, edit_user_path do
        = @user.anonymous_check
    %p 
      = link_to "Please click here to edit your profile", edit_user_path
    - unless @user.timeslots.empty?
      %h4.subheader Your Schedule:
      .scheduling 
        %ul
          - @user.timeslots.each do |timeslot|
            %li
              = link_to timeslot.formatted_start_time, timeslot_path(timeslot)
              = link_to 'X', timeslot_path(timeslot), :method => :delete
              = "Booked" if timeslot.confirmed