config/routes.rb
StartupsAnonymous::Application.routes.draw do

  

  ActiveAdmin.routes(self)

  match '/login',  to: 'sessions#new'
  match '/logout',  to: 'sessions#destroy'

  # resources :users, only: :show
  resource :user, only: [:new, :show, :edit, :create, :update]
  get "/users/:id", to: "users#show", as: :profile

  resource :sessions

  resources :timeslots
  resource :schedule, :controller => :schedule
  resources :password_resets


  match '/listeners', to: 'pages#listeners'
  match '/about', to: 'pages#about'
  match '/resources', to: 'pages#resources'
  root to: 'pages#home'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :user_id, :timeslots_attributes
  
  has_many :timeslots
  belongs_to :user

  accepts_nested_attributes_for :timeslots
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  def show
    @schedule = current_user.schedule
    @timeslots_by_date = Timeslot.group_by_date(@schedule.timeslots)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today   

#one persons schedule

  end

  def edit
    @schedule = current_user.schedule
  end

  # @schedule = current_user.schedule.update(params[:schedule])
  # fat model, skinny controller (find blog post Jamis Buck)
  # ask Andrew why DJ instead of Resque

  def update
    @schedule = current_user.schedule
    @schedule.attributes = params[:schedule]

    if @schedule.save
      flash[:notice] = "Schedule updated."
      redirect_to schedule_path(@schedule)
    else
      flash[:error] = "Oh shoot, there was a problem updating your schedule. Please try again"
      render action: :edit
    end

  end
end

app/views/schedule/show.html.haml
.row.scheduling
  .large-6.columns
    %h2 Your schedule
    - if @current_user.timeslots.present?
      %h4.subheader Please click on a timeslot to edit it 
    %ul
      - @schedule.timeslots.each do |timeslot|
        %li
          = link_to timeslot.formatted_start_time, edit_timeslot_path(timeslot)
          = link_to 'X', timeslot_path(timeslot), :method => :delete
          = "Booked" if timeslot.confirmed
    .button#timeslot
      = link_to "Add new timeslot", new_timeslot_path

  .large-6.columns
    = render 'users/skype', user: @current_user