config/routes.rb
StartupsAnonymous::Application.routes.draw do

  

  ActiveAdmin.routes(self)

  match '/login',  to: 'sessions#new'
  match '/logout',  to: 'sessions#destroy'

  # resources :users, only: :show
  resource :user, only: [:new, :show, :edit, :create, :update]
  get "/users/:id", to: "users#show", as: :profile

  resource :sessions

  resources :timeslots
  resource :schedule, :controller => :schedule
  resources :password_resets


  match '/listeners', to: 'pages#listeners'
  match '/about', to: 'pages#about'
  match '/resources', to: 'pages#resources'
  root to: 'pages#home'
end

app/views/pages/_bio.html.haml
.row
  .large-8.columns.centered
    .row
      .large-12.columns
        %h2{style: 'margin-top: 1rem'} Who We Are
        %p
          We are survivors of failures. We are the ones who laid people off. We made the "I'm sorry" calls to investors. We are the ones who lost friends.
        %p
          But we were also the recipients of great care and love by our friends and family (the same people we felt too much shame to talk to). For as much as we personalized and absorbed our company's failures, a few precious people never stopped caring about us. Sometimes as it happened to us, casual near-strangers reached out because they knew "sometimes, a coffee can mean the world." We are not great, no, but we were lucky.
        %p
          To our eternal regret, we were never able to pay back some of those who were there for us. So we want to pay it forward.
        %p
          = link_to "Diego Prats (@mexitlan)", "http://www.twitter.com/mexitlan", target: "_blank"
        %p
          = link_to "Bobby Matson (@bomatson)", "http://www.twitter.com/bomatson", target: "_blank"

app/views/pages/_listeners.html.haml
.row.listeners
  %h2 Our Listeners
  %ul.inline-list
    %li
      .large-4.columns
        = link_to image_tag('sean-percival.png'), timeslots_path
      .large-8.columns
        .description
          %h3.subheader Sean Percival
          %p
            Sean Percival is an entrepreneur, blogger and online marketing specialist. He was the Co-founder and CEO or Wittlebee and prior to that Vice President, Online Marketing for Myspace. He is known as the "Series A Whisperer" after going through a tough funding situation and sharing his story and advice for other founders. Currently he is a Distribution Specialist at 500 startups        
    %li
      .large-4.columns
        = link_to image_tag('bobby-matson.png', width: 200, height: 200), timeslots_path
      .large-8.columns
        .description
          %h3.subheader Bobby Matson
          %p
            Bobby Matson is an entrepreneur and software developer living in Santa Monica, CA. He co-founded an angel-funded music tech startup while at school in UMichigan. The business, MyBandStock, developed loyalty programs for music artists. Currently, he is developing products with Carbon Five, a Ruby on Rails consultancy in SF/LA. 
    %li
      .large-4.columns
        = link_to image_tag('diego.png'), timeslots_path
      .large-8.columns
        .description
          %h3.subheader Diego Prats
          %p
            Diego Prats a startup veteran and the very first Listener of Startups Anonymous. Currently he is working as a Product manager in SaaS. 

app/views/pages/_mission.html.haml
.row.background_grey.sub
  .large-8.columns.centered
    .row
      .large-12.columns
        %h2 Our Mission
        .mission
          %p
            We are here to lend a non-judgmental ear or mind to anyone going through the hard times. We can of course lend our experience to help you out, and would love to see people climb out of the pit, but we are also there for the "I don't even know what to ask/say" moments.
          %p
            Most people will Fall. Sometimes, the Fall is so hard that people do not try again. We cannot change that, but we can try to make a small dent.

app/views/pages/_resources_heading.html.haml
.row 
  .large-8.columns.centered
    .row
      .large-12.columns
        %h2 Resources
        %h3.subheader
          We will post links and resources we found useful during the hard times.
        %p
          The first link below is Teddy Roosevelt’s “Citizenship in the Republic” which a friend sent to Diego Prats, as had been sent to the friend, in a long chain of people refactoring their lives.
        %p
          = link_to 'Citizenship in a Republic', "http://en.wikipedia.org/wiki/Citizenship_in_a_Republic"

app/views/pages/about.html.erb
<% provide(:title, 'About') %>

<%= render "bio" %>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>

<div class='homepage'>
  <section class="hero text-center">
    <%= image_tag 'logo.png' %>
    <div class='hero-text'>
      startups anonymous
    </div>
  </section>

  <section class="blue-container">
    <div class='row'>
      <div class='small-12 columns'>
        <h1 class='text-center'>Startups Fail. All the time.</h1>
        <p>
        Some "wind down" and others crash, burning the last people
        crazy enough to be on the rocket. We in the tech world, logically,
        focus on the successes and the bets won. Geniuses. Closers. We are
        here for the others (in this current moment, because it is a long
        game after all), the negative space formed by Great Figures.
        </p>
      </div>
    </div>
  </section>

  <section class="coffee-container text-center">
    <h1>Sometimes a coffee can mean the world.</h1>
  </section>

  <section class="mission-container">
    <div class='row'>
      <div class='small-12 columns'>
        <h1 class='text-center'> Our Mission </h1>
        <p>
        We are here to lend a non-judgmental ear or mind
        to anyone going through the hard times. We can of
        course lend our experience to help you out, and
        would love to see people climb out of the pit,
        but we are also there for the "I don't even know
        what to ask/say" moments.
        </p>
        <p>
        Most people will Fall. Sometimes, the Fall is so
        hard that people do not try again. We cannot change
        that, but we can try to make a small dent.
        </p>
      </div>
    </div>
  </section>

  <section class='cta-container text-center'>
    <h1>How to get in touch</h1>
    <div class='row'>
      <div class='small-12 columns'>
        <%= image_tag('email.png') %>
        <div class='contact-detail'>
          <b>Email us</b> and we will reply immediately.
        </div>
      </div>

      <div class='small-12 columns'>
        <%= image_tag('skypee.png') %>
        <div class='contact-detail'>
          <b>Call us</b> using Burnr or Skype by setting up a time below.
        </div>
      </div>

      <div class='small-12 columns'>
        <%= image_tag('coffee_cup.png') %>
        <div class='contact-detail'>
          <b>Let's grab coffee</b> if you live in the Los Angeles or Bay Area.
        </div>
      </div>

      <div class='disclaimer small-12 columns text-left'>
        <small>
          *Please note: It is a small world. We want people to be
          as open as possible, so we recommend people know
          <%= link_to "our real names", listeners_path %> to make sure
          we are as open as possible. Anyone can contact us anonymously
          or with their real name. We can also put you in touch with someone
          else in case you prefer to not talk to Bobby or Diego.
        </small>
      </div>
    </div>

    <%= render 'users/new' unless signed_in? %>
  </section>
</div>

app/views/pages/listeners.html.haml
- provide(:title, "Listeners")
= render "listeners"

app/views/pages/resources.html.erb
<% provide(:title, 'Resources') %>

<%= render "resources_heading" %>