config/routes.rb
StartupsAnonymous::Application.routes.draw do

  

  ActiveAdmin.routes(self)

  match '/login',  to: 'sessions#new'
  match '/logout',  to: 'sessions#destroy'

  # resources :users, only: :show
  resource :user, only: [:new, :show, :edit, :create, :update]
  get "/users/:id", to: "users#show", as: :profile

  resource :sessions

  resources :timeslots
  resource :schedule, :controller => :schedule
  resources :password_resets


  match '/listeners', to: 'pages#listeners'
  match '/about', to: 'pages#about'
  match '/resources', to: 'pages#resources'
  root to: 'pages#home'
end

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role='navigation'>
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="/">Startups Anonymous</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">

    <ul class="left">
      <li class="divider"></li>
      <li>
        <% if signed_in? %>
        <%= link_to "Listener Availability", timeslots_path %>
        <% end %>
      </li>
      <li>
        <% if signed_in? && current_user.role == "listener" %>
        <%= link_to "My Schedule", schedule_path %>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <% if signed_in? %>
        <%= link_to "My Profile", user_path %>
        <% end %>
      </li>
      <li class="divider"></li>
    </ul>

    <ul class="right">
      <li class="divider"></li>
      <li><a href="/listeners">Listeners</a></li>
      <li class="divider"></li>
      <li><a href="/about">About</a></li>
      <li class="divider"></li>
      <% if signed_in? %>
        <li class="divider"></li>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li class="divider"></li>
        <li><%= link_to "Log in!", login_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title))%></title>

    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,700,100' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% if flash[:error] %>
        <div data-alert class="alert-box alert"><%= flash[:error] %><a href="#" class="close">&times;</a></div>
      <% end %>

      <%if flash[:notice] %>
        <div data-alert class="alert-box"><%= flash[:notice] %><a href="#" class="close">&times;</a></div>
      <% end %>

      <%if flash[:alert] %>
        <div data-alert class="alert-box success"><%= flash[:alert] %><a href="#" class="close">&times;</a></div>
      <% end %>

      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>